version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - db_network

  server:
    build: 
      context: ..
      dockerfile: docker/server/Dockerfile
    volumes:
      - ../Code/Server:/app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - server_network
      - db_network
  
  agent:
    build: 
      context: ..
      dockerfile: docker/client/Dockerfile
    volumes:
      - ../Code/client:/app
    restart: always
    networks:
      - server_network
    depends_on:
      - server

networks:
  server_network:
  db_network: