services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      TZ: "America/Chicago"  # Central Time Zone
    volumes:
      - ./postgres/16-alpine:/var/lib/postgresql/data
    networks:
      - db_network

  server:
    build: 
      context: ..
      dockerfile: docker/server/Dockerfile
    volumes:
      - ../Code/Server:/app
    restart: always
    container_name: server
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      TZ: "America/Chicago"  # Central Time Zone
    networks:
      - server_network
      - db_network
  
  agent:
    build: 
      context: ..
      dockerfile: docker/client/Dockerfile
    volumes:
      - ../Code/client:/app
    restart: always
    environment:
      TZ: "America/Chicago"  # Central Time Zone
    networks:
      - server_network
    depends_on:
      - server


networks:
  server_network:
  db_network: